- id: check-branch-name-length
  name: Check for length of branch name
  description: Checks if a branch name does not exceed the desired length
  entry: check-branch-name-length
  language: python
  pass_filenames: false
  stages: [push]
